services:
  - type: web
    name: coffeestore-django
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn Coffeestore.wsgi
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
